//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HW.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(客戶銀行資訊Metadata))]
    public partial class 客戶銀行資訊
    {
        private class 客戶銀行資訊Metadata
        {
            [Required]
            [StringLength(50)]
            public string 銀行名稱 { get; set; }
            [Required]
            [StringLength(50)]
            public string 帳戶名稱 { get; set; }
            [Required]
            [StringLength(20)]
            public string 帳戶號碼 { get; set; }
        }
    }
}
