//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HW.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(客戶聯絡人Metadata))]
    public partial class 客戶聯絡人
    {
        private class 客戶聯絡人Metadata
        {
            [Required]
            [StringLength(50)]
            public string 職稱 { get; set; }
            [Required]
            [StringLength(50)]
            public string 姓名 { get; set; }
            [Required]
            [StringLength(250)]
            [EmailAddress]
            public string Email { get; set; }
            [StringLength(50)]
            [RegularExpression(@"\d{4}-\d{6}")]
            public string 手機 { get; set; }
            [StringLength(50)]
            public string 電話 { get; set; }
        }
    }
}
